[package]
name = "cli"
version = "0.1.0"
authors = ["Inver <jankowskipawelxd@gmail.com>"]
edition = "2018"

[dependencies]
tokio = { version = "*", features = ["full"] }
clap = "3.0.0-beta.2"
ureq = "2.1.1"
common = { path = "../common" }
webserver = { path = "../webserver" }